services:
  telegram_bot:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - rabbitmq_network
      - ethernet_network

    environment:
      TG_BOT_TOKEN: ${TG_BOT_TOKEN}
      TG_BOT_ID_CHAT: ${TG_BOT_ID_CHAT}

      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DNS: ${RABBITMQ_DNS}

    restart: always


networks:
  rabbitmq_network:
    external: true
    name: rabbitmq_network


  ethernet_network:
    external: true
    name: ethernet_network
